config/routes.rb
Thebeatenpath::Application.routes.draw do
  match "signup" => 'users#new', :as => "signup"
  match "login" => 'sessions#new', :as => "login"
  match "logout" => 'sessions#destroy', :as => "logout"

  get "favorites/:id/save/" => 'favorites#save', :as => 'save_favorite'
  get "searches/:id/new" => 'searches#new', :as => 'yelp_search'
  get "searches/:id/index" => 'searches#index', :as => 'yelp_search_index'

  resources :searches
  resources :sessions, :except => [:edit, :update, :index]
  resources :favorites
  resources :users

  root :to => 'favorites#new'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :searches

  attr_accessible :name, :from, :to, :is_saved, :user_id
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  skip_before_filter :require_authentication
  skip_before_filter :require_admin_authentication

  def index # figure out later, probably apart of user experience/top 10
    @favorites = Favorite.all
  end

  def show # shows gmaps results
    @favorite = Favorite.find(params[:id])
    # @coords = @favorite.searches.map{|x| {"description" => x.name, "lng" => Geocoder.coordinates(x.address)[1].to_s, "lat" => Geocoder.coordinates(x.address)[0].to_s}}

  end

  def save
    @favorite = Favorite.find(params[:id])

    if !session[:user_id].blank?  #if the session has started i.e. the customer is logged in
      @user = User.find(session[:user_id])  #grab the user object
      @user.favorites << @favorite  #update the bridge table to associate the user and favorite
      @favorite.update_attributes(:is_saved => true) # marks the favorite as having been saved (may be redundant)
      redirect_to root_path
    else
      @user = User.new
      @favorite = Favorite.find(params[:id]) #if not logged in, grab the favorite object to be used after the login..
      render new_session_path
    end
  end

  def new # searches gmaps for directions, submit goes to create/also homepage ****
    @favorite = Favorite.new

    if !session[:user_id].blank?  #if the session has started i.e. the customer is logged in
      @user = User.find(session[:user_id])  #grab the user object
   end
  end

  def edit # edit field allows one to redo search with pre-pop params
    @favorite = Favorite.find(params[:id])
  end

  def create # saves and creates search from gmaps and then shows
    @favorite = Favorite.new(params[:favorite])

    if @favorite.save
      redirect_to yelp_search_path(@favorite.id)
    else
      render action: "new"
    end
  end

  def update # from edit page (with pre-pop params) updates favorites renders at show page
    @favorite = Favorite.find(params[:id])

    if @favorite.update_attributes(params[:favorite])
      redirect_to yelp_search_index_path(@favorite.id)
    else
      render action: "new"
    end
  end

  def destroy # deletes favorite/search and returns to favorites new/search page/homepage
    @favorite = Favorite.find(params[:id])
    if @favorite.destroy
      redirect_to root_path
    else
      render action: "show"
    end
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_form.html.erb
<%= form_for(@favorite) do |f| %>
  <% if @favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% @favorite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row ">
    <div class="field large-7 large-centered columns">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
  </div><div class="row ">
  <div class="field large-7 large-centered columns">
    <%= f.label :from %><br />
    <%= f.text_field :from %>
  </div>
</div>
<div class="row">
  <div class="field large-7 large-centered columns">
    <%= f.label :to %><br />
    <%= f.text_field :to %>
  </div>
</div>
  <div class="actions large-2 large-centered columns">
    <%= f.submit  "Submit" %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<div class="row">
  <div class="small-6 large-centered columns gm_search_box">
    <h4>Would you like to edit your route?</h4>
    <hr>

      <%= render 'form' %>

      <%= link_to 'Show', @favorite %> |
  </div>
</div>

app/views/favorites/index.html.erb
<h1>Listing All of "The Beaten Paths" favorites</h1>

<table>
  <tr>
    <th>Name</th>
    <th>From</th>
    <th>To</th>
    <th>Looking For</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @favorites.each do |favorite| %>
  <tr>
    <td><%= favorite.name %></td>
    <td><%= favorite.from %></td>
    <td><%= favorite.to %></td>
    <td><%= favorite.searches.pluck("name").join(", ") %></td>
    <td><%= link_to 'Show', favorite %></td>
    <td><%= link_to 'Edit', edit_favorite_path(favorite) %></td>
    <td><%= link_to 'Destroy', favorite, method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Favorite', new_favorite_path %>

app/views/favorites/new.html.erb
<div class="row">
  <div class="large-centered columns gm_search_box">
    <h3>Where would you like to go today?</h3>
    <hr>

<%= render 'form' %>

  <% if !current_user.nil? %>

      <br>
      <hr>

      <% @user.favorites.each do |favorite| %>
      <p id="favorite_show">Name: <%= favorite.name %> |
      Route: From <%= favorite.from %> to <%= favorite.to %> |
   <!--    Looking for:  <%#= favorite.searches.pluck("name").join(", ") %> -->

      <%= link_to 'Show', favorite_path(favorite.id) %> |
      <%= link_to 'Edit', edit_favorite_path(favorite.id) %> |
      <%= link_to 'Destroy', favorite_path(favorite.id), method: :delete %></p>
      <% end %>
  <% end %>

  </div>
</div>

<!-- if logged in , show previous favorites with link to show it -->

app/views/favorites/show.html.erb
<% if !@favorite.name.blank? %>
  <h1>"<%= @favorite.name %>" route</h1>
  <% else %>
  <h1>Your route</h1>
<% end %>

      <% @favorite.searches.each do |search| %>
        <input class="address" type="hidden" value="<%= search.address %>">
      <% end %>



      <input id="start" type="hidden" value="<%= @favorite.from %>">
      <input id="end" type="hidden" value="<%= @favorite.to %>">





<div id="gm_show_box" class="row">
  <div id="map-canvas" class="large-8 columns"></div>
  <div id="directions_panel" class="large-4 columns"></div>
  <div class="row">
    <%if @favorite.is_saved == false %>
      <div class="small-2 columns"><%= link_to 'Save to Favorites', save_favorite_path(:user => {:favorite_id => @favorite.id}) %></div>
    <% else %>
        <div class="small-2 columns"></div>
    <% end %>
      <div class="small-2 columns"><%= link_to 'Edit', edit_favorite_path(@favorite) %></div>
      <div class="small-2 columns"><%= link_to 'Try a new route', root_path %></div>
      <div class="small-3 columns"><%= link_to 'Delete', @favorite, method: :delete %></div>

  </div>
</div> <!-- map and directions -->

<p id="notice"><%= notice %></p>

<div class="row">
  <h1>Yelp Query</h1>
  <table border="1">
    <tr>
      <th>Name</th>
      <th>Yelp_Query</th>
      <th>Search ID</th>
      <th>Fav ID</th>
      <th>Address</th>
      <th>Lat</th>
      <th>Long</th>
    </tr>
    <% @favorite.searches.each do |search| %>
    <tr>
      <td><%= search.name  %></td>
      <td><%= search.yelp_query  %></td>
      <td><%= search.id  %></td>
      <td><%= search.favorite_id %></td>
      <td><%= search.address %></td>
      <td><%= search.latitude  %></td>
      <td><%= search.longitude  %></td>
    </tr>
    <% end %>
  </table>

  <hr>
</div> <!-- table -->

<hr>

app/views/favorites/show.html.erb.BACKUP.59321.erb
<p id="notice"><%= notice %></p>

<h1>Yelp Query</h1>
<table border="1">
  <tr>
    <th>Query</th>
    <th>Search ID</th>
    <th>Fav ID</th>
    <th>Address</th>
    <th>Lat</th>
    <th>Long</th>
  </tr>
  <% @favorite.searches.each do |search| %>
  <tr>
    <td><%= search.yelp_query  %></td>
    <td><%= search.id  %></td>
    <td><%= search.favorite_id %></td>
    <td><%= search.address %></td>
    <td><%= search.latitude  %></td>
    <td><%= search.longitude  %></td>
  </tr>
  <% end %>
</table>

<hr>

<%= link_to 'Save to Favorites', save_favorite_path(:user => {:favorite_id => @favorite.id}) %>
<%= link_to 'Edit', edit_favorite_path(@favorite) %>
<%= link_to 'Destroy', @favorite, method: :delete %>
<hr>


<% @favorite.searches.each do |search| %>
  <input class="marker" type="hidden" value="<%= search.address %>">
<% end %>


<% @favorite.searches.each do |search| %>
  <input class="waypoints" type="hidden" value="<%= search.address %>">
<% end %>

<input id="start" type="hidden" value="<%= @favorite.from %>">
<input id="end" type="hidden" value="<%= @favorite.to %>" onload="calcRoute();">
<<<<<<< HEAD
<div id="map-canvas"></div>
=======

<div>
  <div id="map-canvas"></div>
  <div id="control_panel">
    <div id="directions_panel"></div>
  </div>
</div>

>>>>>>> 45c9c0a7de73a932554476876bd4d1851442534f
<!--   <%#

    coords = Geocoder.coordinates(@favorite.searches.first.address)
    @markers = [{"lat" => coords[0].to_s, "lng" => coords[1].to_s}] %>


 -->

app/views/favorites/show.html.erb.BASE.59321.erb
<p id="notice"><%= notice %></p>

<p>Yelp Query</p>
<% @favorite.searches.each do |search| %>
  <p><%= search.yelp_query  %></p>
  <p>Search id - <%= search.id  %></p>
  <p>Favorite id - <%= search.favorite_id %></p>
  <p>Address - <%= search.address %>
  <% end %>


<%= link_to 'Save to Favorites', save_favorite_path(:user => {:favorite_id => @favorite.id}) %>
<%= link_to 'Edit', edit_favorite_path(@favorite) %>
<%= link_to 'Destroy', @favorite, method: :delete %>
<br>

<input id="start" type="hidden" value="<%= @favorite.from %>">
<input id="end" type="hidden" value="<%= @favorite.to %>" onload="calcRoute();">
<button onclick="calcRoute();">Submit</button>
<div id="map-canvas"></div>
<!--   <%#

    coords = Geocoder.coordinates(@favorite.searches.first.address)
    @markers = [{"lat" => coords[0].to_s, "lng" => coords[1].to_s}] %>


 -->

app/views/favorites/show.html.erb.LOCAL.59321.erb
<p id="notice"><%= notice %></p>

<h1>Yelp Query</h1>
<table border="1">
  <tr>
    <th>Query</th>
    <th>Search ID</th>
    <th>Fav ID</th>
    <th>Address</th>
    <th>Lat</th>
    <th>Long</th>
  </tr>
  <% @favorite.searches.each do |search| %>
  <tr>
    <td><%= search.yelp_query  %></td>
    <td><%= search.id  %></td>
    <td><%= search.favorite_id %></td>
    <td><%= search.address %></td>
    <td><%= search.latitude  %></td>
    <td><%= search.longitude  %></td>
  </tr>
  <% end %>
</table>

<hr>

<%= link_to 'Save to Favorites', save_favorite_path(:user => {:favorite_id => @favorite.id}) %>
<%= link_to 'Edit', edit_favorite_path(@favorite) %>
<%= link_to 'Destroy', @favorite, method: :delete %>
<hr>


<% @favorite.searches.each do |search| %>
  <input class="marker" type="hidden" value="<%= search.address %>">
<% end %>

<input id="start" type="hidden" value="<%= @favorite.from %>">
<input id="end" type="hidden" value="<%= @favorite.to %>" onload="calcRoute();">
<div id="map-canvas"></div>
<!--   <%#

    coords = Geocoder.coordinates(@favorite.searches.first.address)
    @markers = [{"lat" => coords[0].to_s, "lng" => coords[1].to_s}] %>


 -->

app/views/favorites/show.html.erb.REMOTE.59321.erb
<p id="notice"><%= notice %></p>

<p>Yelp Query</p>
<% @favorite.searches.each do |search| %>
  <p><%= search.yelp_query  %></p>
  <p>Search id - <%= search.id  %></p>
  <p>Favorite id - <%= search.favorite_id %></p>
  <p>Address - <%= search.address %>
  <% end %>


<%= link_to 'Save to Favorites', save_favorite_path(:user => {:favorite_id => @favorite.id}) %>
<%= link_to 'Edit', edit_favorite_path(@favorite) %>
<%= link_to 'Destroy', @favorite, method: :delete %>
<br>


<% @favorite.searches.each do |search| %>
  <input class="waypoints" type="hidden" value="<%= search.address %>">
<% end %>

<input id="start" type="hidden" value="<%= @favorite.from %>">
<input id="end" type="hidden" value="<%= @favorite.to %>" onload="calcRoute();">

<div>
  <div id="map-canvas"></div>
  <div id="control_panel">
    <div id="directions_panel"></div>
  </div>
</div>

<!--   <%#

    coords = Geocoder.coordinates(@favorite.searches.first.address)
    @markers = [{"lat" => coords[0].to_s, "lng" => coords[1].to_s}] %>


 -->