config/routes.rb
Thebeatenpath::Application.routes.draw do
  match "signup" => 'users#new', :as => "signup"
  match "login" => 'sessions#new', :as => "login"
  match "logout" => 'sessions#destroy', :as => "logout"

  get "favorites/:id/save/" => 'favorites#save', :as => 'save_favorite'
  get "searches/:id/new" => 'searches#new', :as => 'yelp_search'
  get "searches/:id/index" => 'searches#index', :as => 'yelp_search_index'

  resources :searches
  resources :sessions, :except => [:edit, :update, :index]
  resources :favorites
  resources :users

  root :to => 'favorites#new'

end

app/models/search.rb
# This is for our yelp queries

class Search < ActiveRecord::Base
  attr_accessible :address, :favorite_id, :name, :yelp_query, :latitude, :longitude

  belongs_to :favorite



end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  skip_before_filter :require_authentication
  skip_before_filter :require_admin_authentication

  def index
    @favorite = Favorite.find(params[:id])
  end

  def show
    @search = Search.find(params[:id])
  end

  def new
    @search = Search.new
    @favorite = Favorite.find(params[:id])
  end

  def edit
    @search = Search.find(params[:id])
  end

  def create
    @search = Search.new(params[:search])
    @favorite = Favorite.find(params[:favorite_id])
    @route_pts = JSON.parse(params[:route_pts]) # in searches.js we've added a 5 sec delay; thus if you press the search button too soon it will return 'nil'

    client = Yelp::Client.new

    @route_pts.each do |yelp_request|
      latitude = yelp_request.first
      longitude = yelp_request.last

      request = Yelp::V2::Search::Request::GeoPoint.new(
                  :term => @search.name,
                  :latitude => latitude,
                  :longitude => longitude,
                  :radius=> 1,
                  :consumer_key => "<%= ENV['CONSUMER_KEY'] %>",
                  :consumer_secret => "<%= ENV['CONSUMER_SECRET'] %>",
                  :token => "<%= ENV['TOKEN'] %>",
                  :token_secret => "<%= ENV['TOKEN_SECRET'] %>")

      response = client.search(request)

      two_businesses = response["businesses"].take(2)

      names = two_businesses.map  do |business|
          business["name"]
      end

      # addresses = two_businesses.map do |business|
      #     Geocoder.search("#{latitude}, #{longitude}")
      # end


      addresses = two_businesses.map do |business|
          business["location"]["display_address"].join(' , ')
      end



      addresses.each_with_index do |address, i|
        Search.create(name:@search.name, yelp_query:names[i], favorite_id:@favorite.id, latitude:latitude, longitude:longitude, address:addresses[i])
      end




    end

    # request = Yelp::V1::Review::Request::Location.new(
    #              :address => @favorite["from"],
    #              :radius => 0.1,
    #              :term => @search.name,
    #              :yws_id => '5iVHiSXheAs_WzdKzcYE7g')

    redirect_to favorite_path(@favorite.id)
  end

  def update
    @search = Search.find(params[:id])
    if @search.update_attributes(params[:search])
      redirect_to yelp_search_index_path(@search.favorite.id)
    else
      render action: "new"
    end
  end

  def destroy
    @search = Search.find(params[:id])

    if @search.destroy
      redirect_to yelp_search_index_path(@search.favorite.id)
    else
      render action: "new"
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_for @search do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="field large-6 large-centered columns">
      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </div>
    </div>

    <% if !@favorite.nil? %>
    <input type="hidden" name="favorite_id" value="<%= @favorite.id %>">
    <% end %>

    <div class="actions">
      <%= f.submit "Submit" %>
    </div>
  </div>
<% end %>

app/views/searches/create.html.erb
<h1>Searches#create</h1>
<p>Find me in app/views/searches/create.html.erb</p>

app/views/searches/destroy.html.erb
<h1>Searches#destroy</h1>
<p>Find me in app/views/searches/destroy.html.erb</p>

app/views/searches/edit.html.erb
<h1>Searches#edit</h1>
<p>Find me in app/views/searches/edit.html.erb</p>

<%= render 'form' %>

app/views/searches/index.html.erb
<div class="row">
  <div class="small-6 large-centered columns gm_search_box">
    <h3>Here are all of the things you want to do on your route</h3>
    <hr>

      <% @favorite.searches.each do |search| %>
      <p>
        <%= search.name %>
        - <%= search.yelp_query %>
        <%= link_to 'Destroy', search, method: :delete %></p>

      <% end %>

      <%= link_to 'Add something new to do', yelp_search_path(@favorite.id) %>

      <br>

      <h4>To continue to map, click Submit</h4>
      <hr>
      <%= link_to 'Submit', favorite_path(@favorite.id) %>
  </div>
</div>

app/views/searches/new.html.erb
<div class="row">
  <div class="small-6 large-centered columns gm_search_box">
    <h3>What would you like to do on your way?</h3>
    <hr>

      <%= render 'form' %>

    <hr>
    <div class="row">
      <div id="map-canvas" class="small-6 large-centered columns map_show"></div>
    </div>
  </div>
</div>

      <input id="start" type="hidden" value="<%= @favorite.from %>">
      <input id="end" type="hidden" value="<%= @favorite.to %>">


<input id="route_points" type="hidden" value="<%= @favorite.from %>">

<% content_for :extra_js do %>
<script type="text/javascript">
    setTimeout(function() {do_route_pts()}, 3000);
    var do_route_pts = function() {

      console.log("route pts array:");
      console.log("it is a(n) " + typeof(route_pts));
      console.log(route_pts);
      console.log("----------");
      var route_string = "[";
      console.log("try to loop.....");
      $.each(route_pts, function(k,v) {
        if (k > 0) {
          route_string += " , "
        }
        console.log("in your loop... with:");
        console.log(k);
        console.log(v);
        console.log("---------------");
        route_string += "[" + v[0] + "," + v[1] + "]";
      });
      route_string += "]"
      console.log("route string:");
      console.log(route_string);
      console.log("----------");
      var hidden_input = $('<input type="hidden">')
      hidden_input.attr('name', 'route_pts');
      hidden_input.attr('id', 'route_pts');
      hidden_input.attr('value', route_string);
      $('#new_search').append(hidden_input);
      // document.write('<param name="route_pts" value="' + route_pts + '">');
    };
</script>
<% end %>
<!-- NOTE - this has to  -->

app/views/searches/show.html.erb
<h1>Searches#show</h1>

<div class="row">
  <div id="gm_show_box" class="large-centered-columns">

  </div>
</div>

app/views/searches/update.html.erb
<h1>Searches#update</h1>
<p>Find me in app/views/searches/update.html.erb</p>